[workspace]
members = ["crates/*"]
resolver = "3"

[package]
name = "semtools"
version = "1.0.0"
edition = "2024"
license = "MIT"
description = "Semantic search and document parsing tools for the command line"
repository = "https://github.com/run-llama/semtools"
authors = ["Logan Markewich <logan@runllama.ai>"]
categories = ["command-line-utilities", "text-processing"]
keywords = ["semantic-search", "document-parsing", "cli", "pdf", "search"]
readme = "README.md"

[[bin]]
name = "parse"
path = "crates/parse/src/main.rs"

[[bin]]
name = "search"  
path = "crates/search/src/main.rs"

[dependencies]
# Parse dependencies
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["multipart", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
sha2 = "0.10.8"
hex = "0.4.3"
mime_guess = "2.0.5"
dirs = "5.0.1"

# Search dependencies
model2vec-rs = "0.1.3"
simsimd = "6.5.1"

[workspace.package]
version = "1.0.0"
license = "MIT"
repository = "https://github.com/run-llama/semtools"
authors = ["Logan Markewich <logan@runllama.ai>"]
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.45", features = ["derive"] }
anyhow = "1.0.99"
