name: Secrets SOPS Smoke
on:
  pull_request:
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SOPS decrypt + export env
        uses: ./.github/actions/sops-setup
        with:
          sops_age_key: ${{ secrets.SOPS_AGE_KEY }}
      - name: Show env keys (masked)
        run: |
          if [ -s .env.local ]; then
            echo "Keys in .env.local:" && awk -F= '/^[A-Za-z_][A-Za-z0-9_]*=/{print $1}' .env.local | sed -n '1,120p'
          else
            echo ".env.local is empty (expected if vault is a placeholder)."
          fi
